### ISSUE TITLE
Trans component: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by eloyra** [aralroca/next-translate#1027]
**What version of this package are you using?**
`next-translate`: 2.0.5
`next-translate-plugin`: 2.0.5

**What operating system, Node.js, and npm version?**
Linux, 16.17.0, 8.15.0

**What happened?**
I have a translation entry like this one:
```json
{
    "sections": {
        "loved": {
            "title": "Trusted by gamers all <highlight>over the world</highlight>."
        }
    }
}
```

And I'm trying to use the Trans componente like so:
```tsx
        <Trans
          i18nKey={'sections.loved.title'}
          components={{
            highlight: (
              <span
                className={styles['landing__reviews-showcase__highlight']}
              />
            ),
          }}
        />
```

But I get the mentioned error:
<details>

```
index.js?4755:260 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at formatElements (/home/eloyra/Projects/tacter-spa/node_modules/next-translate/lib/cjs/formatElements.js:39:23)
    at <unknown> (/home/eloyra/Projects/tacter-spa/node_modules/next-translate/lib/cjs/Trans.js:16:45)
    at Object.useMemo (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at useMemo (/home/eloyra/Projects/tacter-spa/node_modules/react/cjs/react.development.js:1650:21)
    at Trans (/home/eloyra/Projects/tacter-spa/node_modules/next-translate/lib/cjs/Trans.js:12:38)
    at renderWithHooks (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/eloyra/Projects/tacter-spa/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
```

</details>

**What did you expect to happen?**
I expected the Trans component to correctly render my translation, according to the documentation.

**Are you willing to submit a pull request to fix this bug?**
Not short term.

**Comment by eloyra** [comment]
Interestingly enough, if I use the `TransText` component, it works as expected:
```tsx
<TransText
          text={t('sections.loved.title')}
          components={{
            highlight: (
              <span
                className={styles['landing__reviews-showcase__highlight']}
              />
            ),
          }}
        />
```

Am I missing something regarding the `Trans` component? :thinking:

**Comment by aralroca** [comment]
You need to specify the namespace `i18nKey={'namespace:sections.loved.title'}`

**Comment by eloyra** [comment]
That works, thanks a lot for the support!
