### ISSUE TITLE
New Example Needed

### ISSUE THREAD

**Issue by mlnima** [aralroca/next-translate#1062]
I love this library because it is optimized and easy to setup. 

since Next v13.4.4 I have been trying to install something that works fine with app dir. your example is outdated and is not match with NextJs Doc they ask to create a [lang] route but you do not. would you please make a new example that takes the local from params like the standard Doc and not from a query? or if we can pass the locale as an arg in t() function would be great. 

you know we need to keep the code closest as possible to the standard doc since Vercel has massive changes fetish

**Comment by aralroca** [comment]
There are some compatibility bugs with the new version of Next.js. Try:

- `next-translate` version `2.3.0-canary.3`
- `next-translate-plugin` version `2.3.0-canary.3`

**Comment by TomJD** [comment]
We would appreciate an example as well. 

Also side-question @aralroca , does this work with `generateStaticParams()` ?

If so, and if the [lang] param can be used instead of query parameter, we will switch our project to use your library

**Comment by aralroca** [comment]
thanks for asking. I'm not sure 100%. Currently is used the `lang` param is in appDir. So probably yes, I didn't tried `generateStaticParams` yet.  But good point to verify it

**Comment by TomJD** [comment]
I'm working on an example, with `generateStaticParams()`. This all seems to be working, but the redirects I cannot get working at the moment. It seems that `NextRequest` does not contain the `[lang]` value from the `app` folder path. Is this expected behaviour? 

Happy to add a minimal repro if the `[lang]` param should be included here for a review.

**Comment by aralroca** [comment]
All the routing part is part of Next.js core. I'm not sure if is a bug from this library, but yes, it can be useful a reproducible example to help us to detect what is happening. Thanks

**Comment by mlnima** [comment]
I've built a headless CMS and everything is fine with page router. 
Now we need to swith to app router because who knows when they will stop support for page router. 

since they do not have a support for tons of things like styling libraries I was using.
I created a totaly new Nextjs app in my TurboRepo and wanna rebuild the entire app 

In the old page router project for i18n handler I decided to user no prefix for the default language so for example "/" will be English and
other routes are like "/de","/fr"

the doc on NextJs site ignores this feature in the app router and want us to redirect the user with no local to the default language for example "/en"
since I have several websites online with old routing, making this change will hurt my SEO and Google search console will send tons of Emails about not found,
Yes, I can generate canonical url for them but still, there will be so many issues.

I've tried the way you show in example and example from the NextJs doc along with some other i18n libraries and none of them working yet.

we appreciate if you make an advance example using [lang] in the app router with a nice middleware.ts which handles the new app router like page router.

It's the 7th day I am trying to do this and searching everywhere even asked GPT4 + browser plugin for help

In case I solve the issue will share the code here.

Thank you

**Comment by aralroca** [comment]
@mlnima we have an example inside the `examples` folder: https://github.com/aralroca/next-translate/blob/master/examples/with-app-directory/README.md, however, probably needs some fixes from the last Next.js v.13.4 that we are working in order to fix it.

**Comment by TomJD** [comment]
@aralroca in fact that example is enough for my use-case. If you add the middleware file and `console.log(request.nextUrl)`, you will see that the `pathname` is always `/` for when there is a locale present in the path.

```
{
  href: 'http://localhost:3001/es',
  origin: 'http://localhost:3001',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:3001',
  hostname: 'localhost',
  port: '3001',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {  },
  hash: ''
}
```

For this same reason, my redirects are not working when they start with `/en` `/es` etc.

I know the deps are previous to current versions, but it's the same behaviour.

**Comment by aralroca** [comment]
I think that the pathname without the locale is correct, at least is how i18n routing from Next.js core works in pages folder too.

**Comment by mlnima** [comment]
![image](https://github.com/aralroca/next-translate/assets/39328836/3c421228-ce8d-4c87-9bec-e5f86956f835)

These are 2 different languages I wanna rewrite, when there is no [lang] folder in the App router, EN version works on the path "/" and "/de" does not, 

When there is [lang] folder all the language works except "/"

NextJs example is old as a fossil and they are just trying to solve none existing problem in every update, I am genuinely suffering now

**Comment by aralroca** [comment]
Probably is related with this Next.js issue https://github.com/vercel/next.js/issues/49883

**Comment by mlnima** [comment]
Yes, exactly since the stable release of the app dir it became a big issue. 

May I ask you a favor? 
Since the docs want us to create [lang], could you add 2 features?

1. Ability to read the local from "[lang]" folder and not from "?lang=:lang" for people who need it.
2. Ability to pass the lang as arg in "{t}" function using "useTranslation(':namespace')",
    when we use [lang] it is very easy to get it as params inside layout, so we can pass it as a prop or something   

Thank you in advance

**Comment by mlnima** [comment]
Thank you so much, You are the best, Still trying to find a way to handle the "/" as the default language but it's all from NextJS it self.

**Comment by aralroca** [comment]
@mlnima You can do it using redirect from next/navigation, example https://github.com/aralroca/next-translate/blob/8b3e21f6920fd3d1d38f8933b7e80db4615f75fc/examples/with-app-directory/src/app/%5Blang%5D/layout.tsx#L12

**Comment by mkue** [comment]
Thanks for the example project. It works nicely.

Unfortunately, I fail to make it work with the `generateStaticParams` export. I added the following function to [layout.tsx](https://github.com/aralroca/next-translate/blob/master/examples/with-app-directory/src/app/%5Blang%5D/layout.tsx):

```ts
export const generateStaticParams = () => i18n.locales.map((lang) => ({ lang }));
```

But then, building the project fails with the following error:

```
Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error
Error: The provided export path '/' doesn't match the '/[lang]/page' page.
Read more: https://nextjs.org/docs/messages/export-path-mismatch
    at /Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/export/worker.js:156:27
    at Span.traceAsyncFn (/Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/trace/trace.js:103:26)
    at Object.exportPage (/Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/export/worker.js:96:27)
    at execFunction (/Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2828)
    at execHelper (/Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2486)
    at execMethod (/Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2574)
    at process.messageListener (/Users/mkue/Desktop/next-translate-master/examples/with-app-directory/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1284)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Do you have any idea how this can be resolved? I guess it's related to [this](https://github.com/vercel/next.js/issues/46622) issue?

**Comment by aralroca** [comment]
@mkue no idea, but it looks related to the Next.js issue that you said...
