### ISSUE TITLE
App directory [lang] paths return 404 from NextJS v13.4.13

### ISSUE THREAD

**Issue by nickderobertis-ch** [aralroca/next-translate#1142]
**What version of this package are you using?**

v2.5.3

**What operating system, Node.js, and npm version?**

MacOS, v18.7.0, 8.15.0

**What happened?**

Navigating to app directory pages with the `[lang]` path parameter returns 404 when NextJS is upgraded to [13.4.13](https://github.com/vercel/next.js/releases/tag/v13.4.13) or later.

I have created a simple reproduction of the issue [in this repo](https://github.com/nickderobertis-ch/with-next-translate-app). I simply used the [NextJS official example for next-translate](https://github.com/vercel/next.js/tree/deprecated-main/examples/with-next-translate). When I first started it up it was working, but then once I upgraded NextJS and restarted the server, it started getting 404. I tried different versions of NextJS until I found that v13.4.12 works but v13.4.13 and later do not.

**What did you expect to happen?**

Page loads successfully.

**Are you willing to submit a pull request to fix this bug?**

I am motivated to get this fixed quickly, so I would be willing to help but I am not familiar with the internals of `next-translate` or `next`. With some guidance I would be happy to do the heavy lifting.

There are quite a lot of [changes from 13.4.12 to 13.4.13](https://github.com/vercel/next.js/compare/v13.4.12...v13.4.13), so it's not immediately clear why this broke.

**Comment by nickderobertis-ch** [comment]
There were a couple changes around `basePath`, maybe that's a good place to look. 
- https://github.com/vercel/next.js/pull/53174
- https://github.com/vercel/next.js/pull/53189

**Comment by abuu-u** [comment]
next.config.js

setting i18n to undefined worked for me, idk if this has any drawbacks

```
const nextTranslate = require("next-translate-plugin");
const config = nextTranslate({});
config.i18n = undefined;

module.exports = config;
```

**Comment by oscarrc** [comment]
> next.config.js
> 
> setting i18n to undefined worked for me, idk if this has any drawbacks
> 
> ```
> const nextTranslate = require("next-translate-plugin");
> const config = nextTranslate({});
> config.i18n = undefined;
> 
> module.exports = config;
> ```

I can confirm this removes the issue, it also helps with https://github.com/aralroca/next-translate/issues/1141, but, as you've said, I don't know what the drawbacks could be.

**Comment by nickderobertis-ch** [comment]
> setting i18n to undefined worked for me, idk if this has any drawbacks

Nice find, this seems like a good workaround if only `app` directory is used. The `i18n` attribute is still used for the `pages` directory. In our case, we have an existing application on `pages` and are trying to migrate it to `app` directory incrementally, so we need it working in both.

**Comment by oscarrc** [comment]
The problem is Next.js normalizes `nextUrl.pathname` by removing the locale when i18n config is present. But you're right, the config needs to be present in the case of incremental migration, so I think this is something that needs to be solved in their end.

**Comment by nickderobertis-ch** [comment]
I actually found a bug on the NextJS side that may be the cause of this: https://github.com/vercel/next.js/issues/53724

**Comment by deifos** [comment]
Setting i18n to undefined solved my problem but now I see that the locale in the request.nextUrl is removed by nextJS, any work arounds for this?

**Comment by bruno-gurgel** [comment]
Same here. Setting i18n to undefined fixes the issue but I would love a more permanent and less hacky solution

**Comment by aralroca** [comment]
The `i18n` is there to support migration from `pages` to `app`, `i18n` is required for pages, but not for `app`. Feel free for now to remove it. Probably we are going to drop the support for the migration from `pages` to `app` BECAUSE NEXT.JS is not supporting this migration, there are a lot of issues to have the `i18n` in app router, when this `i18n` should be used only in `pages` without interfering to `app` router... :/

**Comment by Zagorakiss** [comment]
Hi everyone.
`config.i18n = undefined;` solved the issue.

But now i'm getting errors during production build while nextjs is generating static pages:
```
Error occurred prerendering page "/500".
RangeError: Incorrect locale information provided
```
```
Error occurred prerendering page "/404".
RangeError: Incorrect locale information provided
```
```
Export encountered errors on following paths:
        /_error: /404
        /_error: /500
```

I tried to bring back i18n to next config (removed line `config.i18n = undefined;`) -> got previous issue but `next build` completed without errors.

I'm not using pages folder so would like to continue using `config.i18n = undefined;` because it makes application behaviour more predictable.
For more context: i don't have custom error pages. Errors occurred in default nextjs error pages.

**Comment by Zagorakiss** [comment]
> Hi everyone. `config.i18n = undefined;` solved the issue.
> 
> But now i'm getting errors during production build while nextjs is generating static pages:
> 
> ```
> Error occurred prerendering page "/500".
> RangeError: Incorrect locale information provided
> ```
> 
> ```
> Error occurred prerendering page "/404".
> RangeError: Incorrect locale information provided
> ```
> 
> ```
> Export encountered errors on following paths:
>         /_error: /404
>         /_error: /500
> ```
> 
> I tried to bring back i18n to next config (removed line `config.i18n = undefined;`) -> got previous issue but `next build` completed without errors.
> 
> I'm not using pages folder so would like to continue using `config.i18n = undefined;` because it makes application behaviour more predictable. For more context: i don't have custom error pages. Errors occurred in default nextjs error pages.

ah...
checked new release (2.6.2) and it contains this fix.
thank you.

**Comment by BjoernRave** [comment]
okay, so I am on `2.6.2` and using only the app router. I am not removing `i18n` from the `next.config.js` object anymore, but then I get the following error:

```
Error occurred prerendering page "/en/dashboard/products". Read more: https://nextjs.org/docs/messages/prerender-error
Error: The provided export path '/dashboard/products' doesn't match the '/[lang]/dashboard/products' page.
Read more: https://nextjs.org/docs/messages/export-path-mismatch
    at getParams (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/export/helpers/get-params.js:27:15)
    at exportPageImpl (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/export/worker.js:86:47)
    at /Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/export/worker.js:214:22
    at Span.traceAsyncFn (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/trace/trace.js:105:26)
    at Object.exportPage (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/export/worker.js:213:41)
    at execFunction (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2764)
    at execHelper (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2422)
    at execMethod (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2510)
    at process.messageListener (/Users/bjoernrave/projects/valooba-mono/apps/pds/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1228)
 ✓ Generating static pages (24/24) 

> Export encountered errors on following paths:
        /[lang]/dashboard/order-history/page: /de/dashboard/order-history
        /[lang]/dashboard/order-history/page: /en/dashboard/order-history
        /[lang]/dashboard/production/page: /de/dashboard/production
        /[lang]/dashboard/production/page: /en/dashboard/production
        /[lang]/dashboard/products/page: /de/dashboard/products
        /[lang]/dashboard/products/page: /en/dashboard/products
        /[lang]/dashboard/service-calls/page: /de/dashboard/service-calls
        /[lang]/dashboard/service-calls/page: /en/dashboard/service-calls
        /[lang]/dashboard/settings/page: /de/dashboard/settings
        /[lang]/dashboard/settings/page: /en/dashboard/settings
        /[lang]/dashboard/table-plan/page: /de/dashboard/table-plan
        /[lang]/dashboard/table-plan/page: /en/dashboard/table-plan
        /[lang]/dashboard/time-tracking/page: /de/dashboard/time-tracking
        /[lang]/dashboard/time-tracking/page: /en/dashboard/time-tracking
        /[lang]/page: /de
        /[lang]/page: /en
        /_error: /404
        /_error: /500
        /_error: /de/404
        /_error: /de/500
        /_error: /en/404
        /_error: /en/500
```

Anyone has the same problem or knows how to fix?

**Comment by kakxem** [comment]
Hi, `config.i18n = undefined;` solved my issue too. 

It was hard to find this fix because I wasn't aware that the error started with version 13.4.13. (I upgraded from 13.4.12 to 14.0.0)

Should we update the README with this fix or wait for a better one?

Thanks!

**Comment by vonsa** [comment]
I'm using pages router and I have a redirect issue on the newer next.js version.

I use this as a temporary solution:
```
const config = nextTranslate(nextConfig);
config.i18n.localeDetection = false;

module.exports = config;
```

If it also works for you, it's atleast better than setting i18n to undefined I guess?

**Comment by aralroca** [comment]
Can you tried in [3.0.0-canary.1](https://github.com/aralroca/next-translate/releases/tag/3.0.0-canary.1) version? (both, next-translate & next-translate-plugin). Thanks

**Comment by federicogomezlara** [comment]
One thing that wasn't noted, or maybe it's just me, @abuu-u's solution causes fast refresh to break, I am forced to disable translations while developing if I want fast refresh to work

**Comment by razzeee** [comment]
Setting `config.i18n = undefined;` to undefined makes the app router routes work, but break everything that's still in the pages router. So we can't migrate at all.

**Comment by BjoernRave** [comment]
I think at this point you should consider moving to sth like https://next-intl.dev/ the migration process is not too bad and things work as expected over there

**Comment by razzeee** [comment]
Sorry, I thought this was on the next repo anyway, was this ever raised over there?
