### ISSUE TITLE
Next.js app build fails due to empty lang value

### ISSUE THREAD

**Issue by wldhg** [aralroca/next-translate#1162]
**What version of this package are you using?**

2.6.1 (same for the plugin)

**What operating system, Node.js, and npm version?**

Ubuntu 22.04.3 / 20.8.0 / 10.1.0

I used pnpm 8.8.0 to install dependencies

Next.js 13.5.4 with App router and middleware which adds /[lang] prefix 

**What happened?**

Build failure occurred with below logs

```
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/11)  [    ]next-translate - compiled page: / - locale: ko - namespaces: common, meta - used loader: server /layout
next-translate - compiled page: / - locale: ko - namespaces: common, meta - used loader: server /layout
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (/home/wldh/my_nextjs_project/node_modules/.pnpm/next-translate@2.6.1_next@13.5.4_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
    at Wc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (/home/wldh/my_nextjs_project/node_modules/.pnpm/next-translate@2.6.1_next@13.5.4_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
    at Wc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
   Generating static pages (7/11)  [=   ] 
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (/home/wldh/my_nextjs_project/node_modules/.pnpm/next-translate@2.6.1_next@13.5.4_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
    at Wc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (/home/wldh/my_nextjs_project/node_modules/.pnpm/next-translate@2.6.1_next@13.5.4_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
    at Wc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/wldh/my_nextjs_project/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
 ✓ Generating static pages (11/11) 

> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
 ELIFECYCLE  Command failed with exit code 1.
```

**What did you expect to happen?**

I expected the build to succeed so I would have time to drink coffee

**Are you willing to submit a pull request to fix this bug?**

I looked into the part where the error occurred, I console.log-ed the input value of `I18nProvider`, it was as follows.

```
{
  lang: undefined,
  namespaces: undefined,
  config: {
    skipInitialProps: true,
    isLoader: true,
    loadLocaleFrom: [Function (anonymous)]
  },
  children: {
    '$$typeof': Symbol(react.element),
    type: [Function (anonymous)],
    key: null,
    ref: null,
    props: { Component: [Function], pageProps: [Object], router: [ez] },
    _owner: null
  }
}
```

In my case, `lang` was set to an empty string as a fallback [(line 24)](https://github.com/aralroca/next-translate/blob/38524fa89a42029d3c62eae90d95e2adb7dead9f/src/I18nProvider.tsx#L24), and an error occurred on [line 28](https://github.com/aralroca/next-translate/blob/38524fa89a42029d3c62eae90d95e2adb7dead9f/src/I18nProvider.tsx#L28).

In my case, this issue was resolved by adding an empty string to the fallback value of localesToIgnore on [line 26](https://github.com/aralroca/next-translate/blob/38524fa89a42029d3c62eae90d95e2adb7dead9f/src/I18nProvider.tsx#L26) as shown below.

```
  const localesToIgnore = config.localesToIgnore || ['default', '']
```

I haven't thoroughly analyzed exactly which cases cause this problem (I suspect it may be related to using `next-translate` in the top-level `layout` file), but just looking at the program logic, I think this modification is not bad.

**Comment by hokidoki** [comment]
I have similar issue.

in my case app/layout.js render client component. and client component call useTranslation. first time has lang but when I refreshed browser, it just empty lang

**Comment by vhpx** [comment]
Same issue here, the problem occurs when the core and the plugin packages get updated from v2.6.0 to v2.6.1.

----------
Might be helpful:
- Failing dependency update PR: https://github.com/tutur3u/tutur3u/pull/972
- Failing CI/CD build log:
```bash
✓ Compiled successfully
     Linting and checking the validity of types ...
     Collecting page data ...
   ⚠ Using edge runtime on a page currently disables static generation for that page
     Generating static pages (0/19) ...
  RangeError: Incorrect locale information provided
      at new PluralRules (<anonymous>)
      at I18nProvider (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/next-translate@2.6.0_next@13.5.6_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
      at Wc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at $c (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
  
  Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
  RangeError: Incorrect locale information provided
      at new PluralRules (<anonymous>)
      at I18nProvider (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/next-translate@2.6.0_next@13.5.6_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
      at Wc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:[44](https://github.com/tutur3u/tutur3u/actions/runs/6573764237/job/17857443542?pr=972#step:7:45))
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:[48](https://github.com/tutur3u/tutur3u/actions/runs/6573764237/job/17857443542?pr=972#step:7:49)1)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at $c (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
  RangeError: Incorrect locale information provided
      at new PluralRules (<anonymous>)
      at I18nProvider (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/next-translate@2.6.0_next@13.5.6_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
      at Wc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at $c (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
  
  Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
  RangeError: Incorrect locale information provided
      at new PluralRules (<anonymous>)
      at I18nProvider (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/next-translate@2.6.0_next@13.5.6_react@18.2.0/node_modules/next-translate/lib/cjs/I18nProvider.js:57:23)
      at Wc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:2[53](https://github.com/tutur3u/tutur3u/actions/runs/6573764237/job/17857443542?pr=972#step:7:54))
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:[70](https://github.com/tutur3u/tutur3u/actions/runs/6573764237/job/17857443542?pr=972#step:7:71):481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:[76](https://github.com/tutur3u/tutur3u/actions/runs/6573764237/job/17857443542?pr=972#step:7:77):89)
      at Zc (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
      at Z (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
      at $c (/home/runner/work/tutur3u/tutur3u/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:[78](https://github.com/tutur3u/tutur3u/actions/runs/6573764237/job/17857443542?pr=972#step:7:79):98)
       next-translate - compiled page: /[lang] - locale: en - namespaces: common, notifications - used loader: server /layout
  
     Generating static pages (4/19) 
  next-translate - compiled page: /[lang] - locale: vi - namespaces: common, notifications - used loader: server /layout
  next-translate - compiled page: /[lang] - locale: en - namespaces: common, notifications - used loader: server /layout
  next-translate - compiled page: /[lang] - locale: vi - namespaces: common, notifications - used loader: server /layout
  next-translate - compiled page: /[lang] - locale: en - namespaces: common, notifications - used loader: server /layout
  next-translate - compiled page: /[lang] - locale: vi - namespaces: common, notifications - used loader: server /layout
  
     Generating static pages (9/19) 
  next-translate - compiled page: /[lang] - locale: en - namespaces: common, notifications - used loader: server /layout
  next-translate - compiled page: /[lang] - locale: vi - namespaces: common, notifications - used loader: server /layout
  next-translate - compiled page: /[lang] - locale: en - namespaces: common, notifications - used loader: server /layout
```

**Comment by lucasalima** [comment]
Im facing the same issue here.

`> next build

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (1/3)  [=   ]
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\next-translate@2.6.1_next@13.5.6_react@18.2.0\node_modules\next-translate\lib\cjs\I18nProvider.js:57:23)
    at Wc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at $c (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\next-translate@2.6.1_next@13.5.6_react@18.2.0\node_modules\next-translate\lib\cjs\I18nProvider.js:57:23)
    at Wc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at $c (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\next-translate@2.6.1_next@13.5.6_react@18.2.0\node_modules\next-translate\lib\cjs\I18nProvider.js:57:23)
    at Wc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at $c (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
RangeError: Incorrect locale information provided
    at new PluralRules (<anonymous>)
    at I18nProvider (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\next-translate@2.6.1_next@13.5.6_react@18.2.0\node_modules\next-translate\lib\cjs\I18nProvider.js:57:23)
    at Wc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (C:\Users\lucas\Documents\Projects\Just Move\justmove-next-dumbbell\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
 ✓ Generating static pages (3/3)

> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
 ELIFECYCLE  Command failed with exit code 1.`
