### ISSUE TITLE
NextRouter was not mounted 

### ISSUE THREAD

**Issue by TheMikeyRoss** [aralroca/next-translate#1217]
**What version of this package are you using?**
`2.6.2`

**What operating system, Node.js, and npm version?**
Windows 10 
Node: 18.20.3
Npm: 10.7.0

**What happened?**
When i try to build my next.js app I get the following error (for each and every page)

```
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (X:\development\Sikka\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\client\router.js:146:15)
    at I18nProvider (X:\development\Sikka\node_modules\.pnpm\next-translate@2.6.2_next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1__react@18.3.1\node_modules\next-translate\lib\cjs\I18nProvider.js:50:37)
    at Wc (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at Zc (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
    at Z (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at $c (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
    at bd (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:77:404)
    at Z (X:\development\Sikka\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:217)
```

**What did you expect to happen?**

It used to build the app with no issues

**Are you willing to submit a pull request to fix this bug?**
Definitely if I know the cause of the issue

**Comment by TheMikeyRoss** [comment]
Im not using the `i18nProvider` btw

**Comment by TheMikeyRoss** [comment]
This is my `i18n.js` config:

```js
const { ALL_LOCALES, DEFAULT_LOCALE } = require("@shared/constants");

module.exports = {
  locales: ALL_LOCALES,
  defaultLocale: DEFAULT_LOCALE,
  pages: {
    "*": [
      "common",
      "pages",
      "auth",
      "errors",
      "permissions",
      "settings",
      "toast",
      "themes",
      "billing",
      "fields",
      "models",
      "validation",
    ],
  },
  loadLocaleFrom: async (locale, namespace) =>
    import(`../../shared/translations/locales/${locale}/${namespace}`).then(
      (r) => r.default,
    ),
};
```

**Comment by TheMikeyRoss** [comment]
And this is my `next.config.js`

```js

/** @type {import('next').NextConfig} */

const nextTranslate = require("next-translate-plugin");
const { version } = require("./package.json");

const {
  ALL_LOCALES,
  DEFAULT_LOCALE,
  ASSETS_BUCKET_1,
} = require("@shared/constants");

const nextConfig = {
  i18n: {
    locales: ALL_LOCALES,
    defaultLocale: DEFAULT_LOCALE,
    localeDetection: false,
  },
  publicRuntimeConfig: { version },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: ASSETS_BUCKET_1 },
    ],
  },
};

module.exports = (phase, { defaultConfig }) => {
  const configWithTranslate = nextTranslate(nextConfig);
  return configWithTranslate;
};

```

**Comment by TheMikeyRoss** [comment]
![image](https://github.com/aralroca/next-translate/assets/97709651/25bb7cda-b58c-41f0-93b2-fba8e920266f)

For some reason it says the source is `I18nProvider` even though im not using it. (it's supposedly used within next-translate)

**Comment by TheMikeyRoss** [comment]
I went all the way inside the file `..../node_modules/.pnpm/next-translate@2.6.2_next@14.2.3 .........` and commented out this line:

![image](https://github.com/aralroca/next-translate/assets/97709651/974bf814-b1a1-4605-931b-cd77f024f33e)


And now the error is gone and it works fine

**Comment by TheMikeyRoss** [comment]
When I add `use client` to the top of my `_app.tsx` the error is gone but the translations are gone and even some UI

**Comment by zaaakher** [comment]
Try `pnpm add encoding -D` within the next.js app with the build issue.

**Comment by TheMikeyRoss** [comment]
> Try `pnpm add encoding -D` within the next.js app with the build issue.

Oh wow that actually solved it! Thank you very much @zaaakher !

**Comment by TheMikeyRoss** [comment]
That worked locally but the problem still exist in my github action workflow

**Comment by TheMikeyRoss** [comment]
Actuallly now it's happening in other workspaces that I haven't touched in a while but they have `next-translate` in them

**Comment by TheMikeyRoss** [comment]
Im getting the error `NextRouter was not mounted` when I run `next dev` or `next build` 

And I can only fix the issue by commenting the line mentioned here https://github.com/aralroca/next-translate/issues/1217#issuecomment-2144003639


@aralroca Could we possibily add a check if NextRouter is mounted or not?

**Comment by TheMikeyRoss** [comment]
![Uploading image.png…]()

**Comment by zaaakher** [comment]
@TheMikeyRoss What's your `react` and `react-dom` versions?

**Comment by TheMikeyRoss** [comment]
They were `18.3.1` and  I tried lowering the versions of `react` and `react-dom` to `18.2.0` in order to match the ones in next-translate but I still get the same error during build

**Comment by TheMikeyRoss** [comment]
Ok so I created an entirly new next.js app within my mono repo with the following next.config:


```
/** @type {import('next').NextConfig} */
import nextTranslate from "next-translate-plugin";

import {
  ALL_LOCALES,
  DEFAULT_LOCALE,
  ASSETS_BUCKET_1,
} from "@shared/constants";

import { version } from "./package.json";

const nextConfig = {
  i18n: {
    locales: ALL_LOCALES,
    defaultLocale: DEFAULT_LOCALE,
    localeDetection: false,
  },
  publicRuntimeConfig: { version },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: ASSETS_BUCKET_1 },
    ],
  },
};

export default nextTranslate(nextConfig);

```


And I got the same error.

When I remove nextTranslate HOC The error disappear and the build succeeds

**Comment by TheMikeyRoss** [comment]
## This works:

```js
const nextConfig = {
  i18n: {
    locales: ["ar", "en"],
    defaultLocale: "ar",
  },
};

export default nextConfig;
```

## This fails

```js
import nextTranslate from "next-translate-plugin";

const nextConfig = {
  i18n: {
    locales: ["ar", "en"],
    defaultLocale: "ar",
  },
};


export default nextTranslate(nextConfig);
```

**Comment by TheMikeyRoss** [comment]
I downgraded next.js from 14.2.3 to 14.2.2 and still the same issue

**Comment by TheMikeyRoss** [comment]
I've deleted the entire repo and cloned it again and still get the same error

**Comment by TheMikeyRoss** [comment]
@aralroca I tried using next-translate v `3.0.0-canary.4` and now building next.js throws this error:

![image](https://github.com/aralroca/next-translate/assets/97709651/99ef5ded-009d-4e04-801d-a7167667db0d)

**Comment by TheMikeyRoss** [comment]
I downgraded to `3.0.0-canary.2` for both `next-translate` and `next-translate-plugin` and now the `NextRouter was not mounted` error is back

**Comment by TheMikeyRoss** [comment]
I'm absolutely loosing my mind

**Comment by zaaakher** [comment]
> I went all the way inside the file `..../node_modules/.pnpm/next-translate@2.6.2_next@14.2.3 .........` and commented out this line:
> 
> ![image](https://private-user-images.githubusercontent.com/97709651/335895212-974bf814-b1a1-4605-931b-cd77f024f33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDA3NDgsIm5iZiI6MTcxNzU0MDQ0OCwicGF0aCI6Ii85NzcwOTY1MS8zMzU4OTUyMTItOTc0YmY4MTQtYjFhMS00NjA1LTkzMWItY2Q3N2YwMjRmMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIyMzQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Mjc2MjM2NzFhNDA0NDllNTU3NmZmNDlmYmE1NDI1MmFjMzNkMTdmMzhiMTQ5YjZkNDE4ZjZkN2Q2OWE1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DevFlfbzDXmMt5M2PUsEDHzAqAWtmdGpFkjbdGh3BHM)
> 
> And now the error is gone and it works fine

You can use [`patch-package`](https://www.npmjs.com/package/patch-package) to make that change permanent. Or if you're using `pnpm` you can use the built-in patch command `pnpm patch` ([read more](https://pnpm.io/cli/patch))
