### ISSUE TITLE
`next-translate` doesn't work without `src/pages` directory despite running `next build`.

### ISSUE THREAD

**Issue by ryami333** [aralroca/next-translate#892]
**What version of this package are you using?**

Latest.

**What operating system, Node.js, and npm version?**

Not an operating-system, NodeJS or NPM-dependent issue.

**What happened?**

If you were to do `yarn build`, and then remove `src/pages/` (or `pages/`), and then try to run `yarn start` then the application fails to start, producing this error message:

```
yarn run v1.22.18
$ next start -p 80
ready - started server on 0.0.0.0:80, url: [http://localhost:80](http://localhost/)
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '/i18n'
Require stack:
- /node_modules/next-translate/lib/cjs/plugin/index.js
- /node_modules/next-translate/lib/cjs/index.js
- /next.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at nextTranslate (/node_modules/next-translate/lib/cjs/plugin/index.js:33:14)
    at Object.<anonymous> (/next.config.js:63:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/next-translate/lib/cjs/plugin/index.js',
    '/node_modules/next-translate/lib/cjs/index.js',
    '/next.config.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This should be possible (and is possible without `next-translate`) because the application should be entirely encapsulated within `./next/standalone` by the time you've completed a build. This behaviour enables Docker deployment as per [Vercel's boilerplate Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile).

**What did you expect to happen?**

I expect that `next-translate` should only do source-code traversal at build-time and not at runtime, where the source-code may no longer be available.

**Are you willing to submit a pull request to fix this bug?**

No.

**Comment by aralroca** [comment]
@ryami333 just out of curiosity, why do you delete `src/pages`? the next-translate webpack loader (which runs in the build) looks inside `src/pages` to see if `_app.js` exists.

**Comment by ryami333** [comment]
@aralroca thanks for your response, and I'm sorry but I don't currently have the bandwidth to create a repro-repo, but the repro steps are quite simple and you should be able to do so with any existing `next-translate` project:

1. Create a NextJS application
2. Install and configure `next-translate`
3. Run `yarn build`
4. Run `mv src/pages src/pagesBAK`
5. Run `yarn start`

> why do you delete src/pages?

We're not _deleting_ it per-se, rather the opposite. We're doing a build in one Docker image, and then moving all of the build-arfefacts into a "runtime" Docker image. Notably, the `src/` directory, by definition, is not a build artefact. Our runtime Dockerfile looks approximately like this:

```Dockerfile
COPY --from=build /next.config.js ./
COPY --from=build /public ./public
COPY --from=build /locales ./locales
COPY --from=build /.next ./.next
COPY --from=build /node_modules ./node_modules
COPY --from=build /package.json ./package.json
COPY --from=build /i18n.js ./i18n.js

# We currently have to include this line, as a workaround, but shouldn't have to:
COPY --from=build /app/src ./src

ENV NODE_ENV production
EXPOSE 80
CMD ["yarn", "start", "-p", "80"]
```

> the next-translate webpack loader (which runs in the build) looks inside src/pages to see if _app.js exists

I've updated my issue description, I attached the wrong error message when I first opened it which may have indicated that this was assoicated with a webpack loader, but I don't think it it. I hope that makes things clearer. As you can probably tell, during startup `next-translate` does not appear to be traversing `.next/server/pages` for `_app.js` (which _does_ exist) and instead depends on the existence of `src/pages`.

**Comment by marjorg** [comment]
Experiencing the same issue with our image that is based on the NextJS [with-docker](https://github.com/vercel/next.js/tree/canary/examples/with-docker) example.

I'm temporarily copying `pages` into the end stage, but would be nice we didn't have to so the image is slimmer.

**Comment by aralroca** [comment]
Try if is solved in Next-translate 2.0.0-canary.3 👍😊
