### ISSUE TITLE
Can't use next translate in Nextjs 13 Version

### ISSUE THREAD

**Issue by jdniels** [aralroca/next-translate#979]
```
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
TypeError: nextTranslate(...) is not a function
    at Object.<anonymous> (/Users/juandaniel/Projects/EnigmaApps/frontend/enigma-compro/next.config.js:30:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadConfig [as default] (/Users/juandaniel/Projects/EnigmaApps/frontend/enigma-compro/node_modules/next/dist/server/config.js:69:36)
    at async NextServer.prepare (/Users/juandaniel/Projects/EnigmaApps/frontend/enigma-compro/node_modules/next/dist/server/next.js:130:24)
```
    
```
Package Version:     
"next-translate": "^1.6.0",
"next": "13.0.6",
```
Npm/Node: 7.24.2/v14.18.0

next.config.js

```
const nextTranslate = require('next-translate');
module.exports = nextTranslate()({
...
});
```

i've already i18n.json
```
{
  "locales": [
    "en",
    "id"
  ],
  "defaultLocale": "en"
}
```

and folder locales in root project 

```
locales
 -en
 --home.json
 -id
 --home.json
 ```

did i mistake something?

**Comment by darl0ck** [comment]
You should use 
`module.exports = nextTranslate({
...
});`

**Comment by jdniels** [comment]
I've tried, with syntax like this.

but still error

```
module.exports = nextTranslate({})({
...another configs
})
```

**Comment by jdniels** [comment]
```
module.exports = nextTranslate({})({
  compiler: {
    // removeConsole: true,
    styledComponents: {
      minify: true,
      ssr: true
    }
  });
  ```

**Comment by aralroca** [comment]
You should do:

**next.config.js**
```js
module.exports = nextTranslate({
...another next.js config
})
```

**i18n.js**
```js
module.exports = {
...next-translate config
})
```

**Comment by aralroca** [comment]
I close the issue, if it continues to happen after what I said if that comment and we reopen it and see what it can be. But it would have to be fixed with what we commented.

**Comment by vemec** [comment]
Same issue here, fresh install of Next JS 13

```bash
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
```

Node version
```bash
->     v18.12.0
```

`package.json`
```json
"dependencies": {
    "eslint": "8.37.0",
    "eslint-config-next": "13.2.4",
    "next": "13.2.4",
    "next-translate": "^2.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
```


`next.config.js`
```js
const nextTranslate = require('next-translate-plugin')
module.exports = nextTranslate({ experimental: { appDir: true } })
```

**Comment by vemec** [comment]
I needed to install `next-translate-plugin`. Now it works ok

```json
"devDependencies": {
    "next-translate-plugin": "^2.0.4"
  }
```

**Comment by Macumba45** [comment]
Why in localhost works the translations and in producction does not works? I uploaded to vercel server, but i dont know why is not working.... please, help!

**Comment by Aryamol123** [comment]
It is not working in production.Is there any solution??
